# Generated by Django 3.2.7 on 2021-10-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('register_date', models.DateField()),
                ('img_file_path', models.TextField()),
                ('first_grade', models.CharField(max_length=4)),
                ('first_grade_percentage', models.IntegerField()),
                ('second_grade', models.CharField(max_length=4)),
                ('second_grade_percentage', models.IntegerField()),
                ('third_grade', models.CharField(max_length=4)),
                ('third_grade_percentage', models.IntegerField()),
                ('modified_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('cow_sex', models.CharField(blank=True, max_length=4, null=True)),
                ('model_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
